apiVersion: v1
kind: Service
metadata:
  name: Hello-World-web-app-image
spec:
  selector:
    app: Hello-World-web-app-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
